-- Users Table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    account_non_expired BOOLEAN NOT NULL DEFAULT TRUE,
    account_non_locked BOOLEAN NOT NULL DEFAULT TRUE,
    credentials_non_expired BOOLEAN NOT NULL DEFAULT TRUE,
    mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    mfa_secret VARCHAR(255),
    attributes TEXT,
    oauth_provider VARCHAR(50),
    oauth_id VARCHAR(255),
    created_at TIMESTAMP,
    last_login_at TIMESTAMP
);

-- Roles Table
CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    hierarchy_level INTEGER
);

-- Permissions Table
CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    resource_type VARCHAR(50)
);

-- User Roles Mapping
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (role_id) REFERENCES roles(id)
);

-- Role Permissions Mapping
CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id) REFERENCES roles(id),
    FOREIGN KEY (permission_id) REFERENCES permissions(id)
);

-- Documents Table
CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT,
    owner_id BIGINT,
    visibility VARCHAR(50),
    department VARCHAR(100),
    classification VARCHAR(50),
    attachment_id BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (owner_id) REFERENCES users(id)
);

-- File Metadata Table
CREATE TABLE file_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    size BIGINT NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    file_type VARCHAR(50) NOT NULL,
    uploaded_by BIGINT,
    uploaded_at TIMESTAMP NOT NULL,
    FOREIGN KEY (uploaded_by) REFERENCES users(id)
);

-- Refresh Tokens Table
CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    device_info VARCHAR(255),
    ip_address VARCHAR(50),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Password Reset Tokens Table
CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    created_at TIMESTAMP,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    used_at TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Initial Data: Roles
INSERT INTO roles (name) VALUES ('ROLE_USER');
INSERT INTO roles (name) VALUES ('ROLE_MANAGER');
INSERT INTO roles (name) VALUES ('ROLE_ADMIN');

-- Initial Data: Permissions
INSERT INTO permissions (name) VALUES ('READ_DOCUMENT');
INSERT INTO permissions (name) VALUES ('WRITE_DOCUMENT');
INSERT INTO permissions (name) VALUES ('DELETE_DOCUMENT');
INSERT INTO permissions (name) VALUES ('MANAGE_USERS');

-- Initial Data: Role Permissions
-- USER gets READ_DOCUMENT, WRITE_DOCUMENT
INSERT INTO role_permissions (role_id, permission_id) 
SELECT r.id, p.id FROM roles r, permissions p WHERE r.name = 'ROLE_USER' AND p.name IN ('READ_DOCUMENT', 'WRITE_DOCUMENT');

-- MANAGER gets USER permissions + DELETE_DOCUMENT
INSERT INTO role_permissions (role_id, permission_id) 
SELECT r.id, p.id FROM roles r, permissions p WHERE r.name = 'ROLE_MANAGER' AND p.name IN ('READ_DOCUMENT', 'WRITE_DOCUMENT', 'DELETE_DOCUMENT');

-- ADMIN gets ALL permissions
INSERT INTO role_permissions (role_id, permission_id) 
SELECT r.id, p.id FROM roles r, permissions p WHERE r.name = 'ROLE_ADMIN';

-- Initial Data: Demo Users (password is 'password123' encoded with BCrypt)
-- User: user
INSERT INTO users (username, email, password, created_at) 
VALUES ('user', 'user@example.com', '$2a$10$xn3LI/AjqicFYZFruO4.uoVW8.k8.u.2.k.1.1.1.1.1.1.1.1.1', CURRENT_TIMESTAMP);

-- User: manager
INSERT INTO users (username, email, password, created_at) 
VALUES ('manager', 'manager@example.com', '$2a$10$xn3LI/AjqicFYZFruO4.uoVW8.k8.u.2.k.1.1.1.1.1.1.1.1.1', CURRENT_TIMESTAMP);

-- User: admin
INSERT INTO users (username, email, password, created_at) 
VALUES ('admin', 'admin@example.com', '$2a$10$xn3LI/AjqicFYZFruO4.uoVW8.k8.u.2.k.1.1.1.1.1.1.1.1.1', CURRENT_TIMESTAMP);

-- Assign Roles
INSERT INTO user_roles (user_id, role_id) 
SELECT u.id, r.id FROM users u, roles r WHERE u.username = 'user' AND r.name = 'ROLE_USER';

INSERT INTO user_roles (user_id, role_id) 
SELECT u.id, r.id FROM users u, roles r WHERE u.username = 'manager' AND r.name = 'ROLE_MANAGER';

INSERT INTO user_roles (user_id, role_id) 
SELECT u.id, r.id FROM users u, roles r WHERE u.username = 'admin' AND r.name = 'ROLE_ADMIN';
